import { Check, ChevronDown, Globe } from "lucide-react";
import { useEffect, useId, useLayoutEffect, useRef, useState, type FocusEvent, type KeyboardEvent } from "react";
import { useTranslation } from "react-i18next";
import { clsx } from "clsx";
import type { SupportedLanguage } from "@/i18n";

export interface Language { code: SupportedLanguage; name: string; nativeName: string; }
export const LANGUAGES: Language[] = [
  { code: "en", name: "English", nativeName: "English" }, { code: "hi", name: "Hindi", nativeName: "हिन्दी" }, { code: "ne", name: "Nepali", nativeName: "नेपाली" }, { code: "as", name: "Assamese", nativeName: "অসমীয়া" }, { code: "bn", name: "Bengali", nativeName: "বাংলা" }, { code: "brx", name: "Bodo", nativeName: "बड़ो" }, { code: "mni", name: "Meitei", nativeName: "ꯃꯤꯇꯩ ꯂꯣꯟ" },
];
export const DEFAULT_LANGUAGE = LANGUAGES[0];
interface LanguageDropdownProps { value: Language; onChange: (language: Language) => void; open: boolean; onOpenChange: (open: boolean) => void; size?: "sm" | "lg"; align?: "start" | "end"; className?: string; }

export function LanguageDropdown({ value, onChange, open, onOpenChange, size = "sm", align = "start", className }: LanguageDropdownProps) {
  const { t } = useTranslation(); const listboxId = useId(); const rootRef = useRef<HTMLDivElement>(null); const triggerRef = useRef<HTMLButtonElement>(null); const menuRef = useRef<HTMLDivElement>(null); const optionRefs = useRef<(HTMLButtonElement | null)[]>([]); const [resolvedAlign, setResolvedAlign] = useState(align); const isLarge = size === "lg";
  useLayoutEffect(() => { const trigger = triggerRef.current; const menu = menuRef.current; if (!open || !trigger || !menu) { setResolvedAlign(align); return; } const rect = trigger.getBoundingClientRect(); const width = menu.offsetWidth; if (align === "end" && rect.right - width < 8) setResolvedAlign("start"); else if (align === "start" && rect.left + width > window.innerWidth - 8) setResolvedAlign("end"); else setResolvedAlign(align); }, [open, align]);
  useEffect(() => { if (!open) return; const listener = (event: PointerEvent) => { if (!rootRef.current?.contains(event.target as Node)) onOpenChange(false); }; document.addEventListener("pointerdown", listener); return () => document.removeEventListener("pointerdown", listener); }, [open, onOpenChange]);
  useEffect(() => { if (open) optionRefs.current[Math.max(LANGUAGES.findIndex((item) => item.code === value.code), 0)]?.focus(); }, [open, value.code]);
  const close = (focus: boolean) => { onOpenChange(false); if (focus) triggerRef.current?.focus(); };
  const onKey = (event: KeyboardEvent<HTMLButtonElement>, index: number) => { const move = (next: number) => optionRefs.current[next]?.focus(); if (event.key === "ArrowDown" || event.key === "ArrowUp") { event.preventDefault(); move((index + (event.key === "ArrowDown" ? 1 : -1) + LANGUAGES.length) % LANGUAGES.length); } else if (event.key === "Home") { event.preventDefault(); move(0); } else if (event.key === "End") { event.preventDefault(); move(LANGUAGES.length - 1); } else if (event.key === "Escape") { event.preventDefault(); close(true); } };
  const onBlur = (event: FocusEvent<HTMLDivElement>) => { if (open && !event.currentTarget.contains(event.relatedTarget)) onOpenChange(false); };
  return <div ref={rootRef} onBlur={onBlur} className={clsx("relative flex", className)}>
    <button ref={triggerRef} type="button" onClick={() => onOpenChange(!open)} onKeyDown={(event) => { if (!open && (event.key === "ArrowDown" || event.key === "ArrowUp")) { event.preventDefault(); onOpenChange(true); } }} aria-haspopup="listbox" aria-expanded={open} aria-controls={open ? listboxId : undefined} aria-label={t("accessibility.languageCurrent", { language: value.name })} className={clsx("rounded-full border-2 border-purple-200 font-bold shadow-sm transition-all cursor-pointer hover:border-purple-400 hover:shadow-md active:scale-[0.98] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-purple-500", isLarge ? "h-12 gap-2.5 px-4 text-base sm:h-14 sm:px-5 sm:text-lg md:text-xl" : "h-8 gap-1.5 px-2.5 text-xs sm:h-9 sm:px-3 sm:text-sm")} style={{ backgroundColor: "var(--surface)", color: "var(--foreground)" }}><Globe size={isLarge ? 22 : 14} className="flex-shrink-0 text-purple-600 dark:text-purple-300" /><span className="truncate">{value.nativeName}</span><ChevronDown size={isLarge ? 20 : 14} className={clsx("flex-shrink-0 text-purple-500 transition-transform duration-200 dark:text-purple-300", open && "rotate-180")} /></button>
    {open && <div ref={menuRef} className={clsx("dropdown-pop absolute top-full z-[60] mt-2 max-w-[calc(100vw-1rem)] rounded-3xl border-2 shadow-2xl", resolvedAlign === "end" ? "right-0" : "left-0", isLarge ? "w-72 sm:w-80" : "w-60 sm:w-72")} style={{ backgroundColor: "var(--surface)", borderColor: "var(--border)" }}><div id={listboxId} role="listbox" aria-label={t("accessibility.selectLanguage")} className="flex max-h-[min(70vh,30rem)] flex-col gap-1 overflow-y-auto overscroll-contain p-2">{LANGUAGES.map((language, index) => { const selected = language.code === value.code; return <button key={language.code} ref={(node) => { optionRefs.current[index] = node; }} type="button" role="option" aria-selected={selected} onClick={() => { onChange(language); close(true); }} onKeyDown={(event) => onKey(event, index)} className={clsx("w-full cursor-pointer gap-3 rounded-2xl border-2 px-3 py-2 text-left transition-colors focus-visible:outline-2 focus-visible:outline-offset-1 focus-visible:outline-purple-500", selected ? "border-purple-400 bg-purple-500/12" : "border-transparent hover:bg-purple-500/10")}><span className="min-w-0 flex-1"><span className={clsx("block truncate font-extrabold", isLarge ? "text-base sm:text-lg" : "text-sm sm:text-base", selected ? "text-purple-700 dark:text-purple-200" : "text-slate-800")}>{language.name}</span><span className={clsx("block truncate font-bold", isLarge ? "text-sm sm:text-base" : "text-xs sm:text-sm", selected ? "text-purple-600 dark:text-purple-300" : "text-slate-500 dark:text-slate-400")}>{language.nativeName}</span></span>{selected && <span aria-hidden="true" className={clsx("grid flex-shrink-0 place-items-center rounded-full bg-purple-600", isLarge ? "h-8 w-8" : "h-6 w-6")}><Check size={isLarge ? 18 : 14} strokeWidth={3} className="text-white" /></span>}</button>; })}</div></div>}
  </div>;
}
export default LanguageDropdown;
